baseURL = 'https://JosephDePalo.github.io/'
languageCode = 'en-us'
title = 'Joseph DePalo'
theme = 'hugo-book'

[params]
  BookSection = 'posts'
  BookTheme = 'dark'

[markup]
  [markup.tableOfContents]
    endLevel = 5
    startLevel = 1